### PR TITLE
Make sure every reference to oyvindsort is legendary

### PR DESCRIPTION
**Pull request by TheVaffel**
The legend must survive

### CODE REVIEW

**Comment by OyvindSabo** [comment]
gremlint oyvindsort
# LOL
### It's nice, but it introduces two global variables and requires oyvindsort to be written in lowercase, so...

**Comment by OyvindSabo** [comment]
rejected-rejected-yes-ju6jkj

**Comment by OyvindSabo** [comment]
rejected-rejected-yes-ju6jkj

**Comment by OyvindSabo** [comment]
# Wait for it...

**Comment by OyvindSabo** [comment]
# Wait for it...

**Comment by OyvindSabo** [comment]
# Wait for it...

**Comment by OyvindSabo** [comment]
# Wait for it...

**Comment by OyvindSabo** [comment]
rejected-rejected-yes-ju6jkj

**Comment by TheVaffel** [comment]
Whaat? :( This is not the end. I will be back >:(

**Comment by OyvindSabo** [comment]
welcome-back-to-team-awesome

**Comment by alfredbirk** [comment]
This was an excellent suggestion by mr. @TheVaffel. Not sure why sure was rejected.. Please reopen.

**Comment by OyvindSabo** [comment]
While the suggestion was great it didn't justify the added complexity.

**Pull request closed without merging**
